spring.application.name=Podflix

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/podflix?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ks591998
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# REDIS CONFIG
# ===============================
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=1h


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# LOGGING
# ===============================
# logging.level.org.hibernate.SQL=DEBUG

# ===============================
# YOUTUBE API
# ===============================
youtube.api.key=AIzaSyDoouDvoDhKK5LPqsJpAwj9OPyX1HxMCis
youtube.application.name=PodFlix
