# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE (MySQL)
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/podflix?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# REDIS CONFIG
# ===============================
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.redis.time-to-live=1h

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# YOUTUBE API
# ===============================
youtube.api.key=${YOUTUBE_API_KEY}
youtube.application.name=PodFlix
